"""users table

Revision ID: 4dd3d2daaff3
Revises: 
Create Date: 2018-04-01 20:20:44.637118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd3d2daaff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('PatronymicNname', sa.String(length=64), nullable=True),
    sa.Column('SurName', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_Name'), 'user', ['Name'], unique=False)
    op.create_index(op.f('ix_user_PatronymicNname'), 'user', ['PatronymicNname'], unique=False)
    op.create_index(op.f('ix_user_SurName'), 'user', ['SurName'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_SurName'), table_name='user')
    op.drop_index(op.f('ix_user_PatronymicNname'), table_name='user')
    op.drop_index(op.f('ix_user_Name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
